import type { Metadata } from "next";
import "../styles/globals.css";
//import "../styles/menu.css";
import Menu from "@/components/Menu";

import { Quicksand, Roboto } from 'next/font/google';

const quicksand = Quicksand({
  subsets: ['latin'],            // Sous-ensembles requis
  variable: '--font-quicksand',
});

const roboto = Roboto({
  subsets: ['latin'], 
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: " DFA - Development For All ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${quicksand.variable} ${roboto.variable} antialiased`}>
      <body
        className="antialiased font-sans"
      >
        <div className="flex flex-col justify-center ">
          <Menu />
        </div>

        {children}
      </body>
    </html>
  );
}
